config/routes.rb
Invoicer::Application.routes.draw do
  resources :jobs

  resources :blips

  resources :clients

  resources :invoices do
    member do
      get 'printshow'
    end
  end
  
  root :to => "Invoices#index"
  
  match 'invoices/by_date/:year(/:month)' => 'Invoices#index', :constraints => { :year => /\d{4}/ }
 

end

app/models/invoice.rb
class Invoice < ActiveRecord::Base
  belongs_to :client
  has_many :blips
  
  before_create :materialize_client
  before_create :materialize_impost
  before_create :assign_number
    
  scope :for_period, lambda {|ini, lapse| where('date >= ?', ini).where('date < ?', ini + lapse) }
  scope :for_year, lambda {|year| for_period(Date.new(year), 1.year) }
  scope :for_year_and_month, lambda {|year, month| for_period(Date.new(year, month), 1.month) }

  scope :asc, order("created_at ASC")
  
  def base_price
    return blips.map{|b| b.total}.sum
  end

  def iva_price
    self.iva*base_price
  end
  
  def irpf_price
    self.irpf*base_price
  end
  
  def invoice_total
    base_price+iva_price-irpf_price
  end
 
  private
    def materialize_client
      self.client_name = client.name
      self.client_address = client.address
      self.client_zip = client.zip
      self.client_poblacio = client.poblacio
      self.client_ciutat = client.city
      self.client_nif = client.nif
      self.iva = IVA
      self.irpf = IRPF
      self.status = 1
    end
  
    def materialize_impost
      self.iva = 0.18
      self.irpf = 0.15
    end
    
    def assign_number
        y = Time.now.year
        li = Invoice.for_year(y).asc.last
        if (li)
          lin = li.number.split("-").first.to_i
          fn = (lin + 1).to_s.rjust(3,"0")
          self.number = "#{fn}-#{y}"
        else self.number = "001-#{y}"
        end
    end
end

app/controllers/invoices_controller.rb
class InvoicesController < ApplicationController

  # GET /invoices
  # GET /invoices.xml
  def index
    @invoices = if(params[:year]) # year is there and integer
      year = params[:year].to_i
      if (params[:month]) # month is there and integer; but can be zero or over 12!
        month = params[:month].to_i
        Invoice.for_year_and_month(year, month)
      else
        Invoice.for_year(year)
      end
    else
      Invoice.all
    end
    respond_to do |format|
      format.html # index.html.erb
      format.xml  { render :xml => @invoices }
    end
  end
  
  def printshow
    @invoice = Invoice.find(params[:id])
        respond_to do |format|
      format.html # show.html.erb
      format.xml  { render :xml => @invoice }
    end
  end

  # GET /invoices/1
  # GET /invoices/1.xml
  def show
    @invoice = Invoice.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.xml  { render :xml => @invoice }
      format.pdf do
        render :pdf => "factura #{@invoice.number}",
               :encoding => "utf-8"
      end
    end
  end

  # GET /invoices/new
  # GET /invoices/new.xml
  def new
    @invoice = Invoice.new

    respond_to do |format|
      format.html # new.html.erb
      format.xml  { render :xml => @invoice }
    end
  end

  # GET /invoices/1/edit
  def edit
    @invoice = Invoice.find(params[:id])
  end

  # POST /invoices
  # POST /invoices.xml
  def create
    @invoice = Invoice.new(params[:invoice])

    respond_to do |format|
      if @invoice.save
        format.html { redirect_to(@invoice, :notice => 'Invoice was successfully created.') }
        format.xml  { render :xml => @invoice, :status => :created, :location => @invoice }
      else
        format.html { render :action => "new" }
        format.xml  { render :xml => @invoice.errors, :status => :unprocessable_entity }
      end
    end
  end

  # PUT /invoices/1
  # PUT /invoices/1.xml
  def update
    @invoice = Invoice.find(params[:id])

    respond_to do |format|
      if @invoice.update_attributes(params[:invoice])
        format.html { redirect_to(@invoice, :notice => 'Invoice was successfully updated.') }
        format.xml  { head :ok }
      else
        format.html { render :action => "edit" }
        format.xml  { render :xml => @invoice.errors, :status => :unprocessable_entity }
      end
      format.json{ respond_with_bip(@invoice) }
    end
  end

  # DELETE /invoices/1
  # DELETE /invoices/1.xml
  def destroy
    @invoice = Invoice.find(params[:id])
    @invoice.destroy

    respond_to do |format|
      format.html { redirect_to(invoices_url) }
      format.xml  { head :ok }
      format.js
    end
  end
end

app/helpers/invoices_helper.rb
module InvoicesHelper
end

app/views/invoices/_form.html.erb
<%= simple_form_for @invoice  do |f| %>
  <% if @invoice.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@invoice.errors.count, "error") %> prohibited this invoice from being saved:</h2>

      <ul>
      <% @invoice.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :date %><br />
    <%= f.date_select :date %>
  </div>
  
  <%= f.association :client %>
  <div class="field">
    <%= f.label :comment %><br />
    <div id = "comment"><%= f.text_area :comment %></div>
  </div>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/invoices/_invoice.html.erb
<%= div_for invoice do %>
	  <%= invoice.date %>
	  <%= invoice.client.name %>
	  <%= invoice.client_name%>
<% end %>

<div id="blips-notice"></div>
<div id="blips">
	<%= render :partial => invoice.blips %>
</div>

<%= link_to 'Edita', edit_invoice_path(invoice) %>
<%= link_to 'Mostra', invoice_path(invoice) %>
<%= link_to 'Elimina', invoice, :method => :delete, :confirm => "Segur?" %>
<br/>

app/views/invoices/destroy.js.erb
$('#invoice_<%= @invoice.id %>').fadeOut();

app/views/invoices/edit.html.erb
<h1>Editing invoice</h1>

<%= render 'form' %>

<%= link_to 'Show', @invoice %> |
<%= link_to 'Back', invoices_path %>

app/views/invoices/index.html.erb
<h1>Factures</h1>

<table id="invoices">
<% @invoices.each do |i|  %>
<tr id = "invoicetd" >
	<td><%= i.date %></td>
	<td><%= i.number %></td>
	<td><%= i.client_name %></td>
	<td>
		<% i.blips.all.each do |b| %>
			<%=b.description%>
			<br>
		<% end %>
	</td>
	<td>€<%= i.invoice_total %></td>
	<td><%= best_in_place i, :status, :type => :select, :collection => [[1, "Idle"], [2, "Enviada"], [3, "e-Enviada"], [4, "Cobrada"]] %></td>
	<td><%= link_to 'Mostra', invoice_path(i) %></td>
	<td><%= link_to 'Imprimir', printshow_invoice_path(i) %></td>
	<td><%= button_to 'Elimina', i, :confirm => 'Segur?', :method => :delete, :class => "delete", :remote => true %></td>
</tr>	
<% end %>
</table>

<br/>

<%= link_to 'Nova factura', new_invoice_path %>
<%= link_to 'Nou client', new_client_path %>


<%= javascript_tag do %>
  $(document).ready(function() {
    /* Activating Best In Place */
    jQuery(".best_in_place").best_in_place();
  });
<% end %>

app/views/invoices/new.html.erb
<h1>Nueva Factura</h1>

<%= render 'form' %>

<%= link_to 'Back', invoices_path %>

app/views/invoices/show.html.erb
<h2>Factura <%= @invoice.number %></h2>

<%= render :partial => @invoice %>


<br/>
<div id="blips-notice"></div>
<h4>Añadir trabajo</h4>
<%= simple_form_for Blip.new(:invoice => @invoice), :remote => true do |f| %>
  <%= f.error_notification %>
  <div class="inputs">
    <%= f.hidden_field :invoice_id %>
	<%= f.input :date %>
    <%= f.input :description %>
    <%= f.input :ppu, :collection => Job.all.collect { |j| [j.name, j.price]} %>
    <%= f.input :qtt %>
  </div>

  <div class="actions">
    <%= f.submit "Añadir" %>
  </div>
<% end %>




<%= link_to 'Edit', edit_invoice_path(@invoice) %> |
<%= link_to 'Back', invoices_path %> |
<%= link_to 'Print preview', printshow_invoice_path(@invoice) %>