config/routes.rb
Invoicer::Application.routes.draw do
  resources :jobs

  resources :blips

  resources :clients

  resources :invoices do
    member do
      get 'printshow'
    end
  end
  
  root :to => "Invoices#index"
  
  match 'invoices/by_date/:year(/:month)' => 'Invoices#index', :constraints => { :year => /\d{4}/ }
 

end

app/models/blip.rb
class Blip < ActiveRecord::Base
  belongs_to :invoice
  
  
  def total
    return self.qtt * self.ppu
  end
end

app/controllers/blips_controller.rb
class BlipsController < ApplicationController
  # GET /blips
  # GET /blips.xml
  def index
    @blips = Blip.all

    respond_to do |format|
      format.html # index.html.erb
      format.xml  { render :xml => @blips }
    end
  end

  # GET /blips/1
  # GET /blips/1.xml
  def show
    @blip = Blip.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.xml  { render :xml => @blip }
    end
  end

  # GET /blips/new
  # GET /blips/new.xml
  def new
    @blip = Blip.new

    respond_to do |format|
      format.html # new.html.erb
      format.xml  { render :xml => @blip }
    end
  end

  # GET /blips/1/edit
  def edit
    @blip = Blip.find(params[:id])
  end

  # POST /blips
  # POST /blips.xml
  def create
    @blip = Blip.create!(params[:blip])
    flash[:notice] = "Blip added!"
    respond_to do |format|
     # if @blip.save
        format.html { redirect_to(@blip, :notice => 'Blip was successfully created.') }
        format.xml  { render :xml => @blip, :status => :created, :location => @blip }
        format.js
     # else
     #   format.html { render :action => "new" }
     #   format.xml  { render :xml => @blip.errors, :status => :unprocessable_entity }
     # end
    end
  end

  # PUT /blips/1
  # PUT /blips/1.xml
  def update
    @blip = Blip.find(params[:id])

    respond_to do |format|
      if @blip.update_attributes(params[:blip])
        format.html { redirect_to(@blip, :notice => 'Blip was successfully updated.') }
        format.xml  { head :ok }
      else
        format.html { render :action => "edit" }
        format.xml  { render :xml => @blip.errors, :status => :unprocessable_entity }
      end
    end
  end

  # DELETE /blips/1
  # DELETE /blips/1.xml
  def destroy
    @blip = Blip.find(params[:id])
    i = @blip.invoice_id
    @inv = Invoice.find(i)
    @blip.destroy

    respond_to do |format|
      format.html { redirect_to(@inv) }
      format.xml  { head :ok }
      format.js
    end
  end
end

app/helpers/blips_helper.rb
module BlipsHelper
end

app/views/blips/_blip.html.erb
<%= div_for blip do %>

 <%= blip.date %>
 <%= blip.description %>
 <%= blip.price %>
 <%= link_to 'Edit', edit_blip_path(blip) %>
<%= link_to 'Elimina', blip, :method => :delete %>



<% end %>

app/views/blips/_form.html.erb
<%= simple_form_for(@blip) do |f| %>
  <%= f.error_notification %>

  <div class="inputs">
    <%= f.input :invoice_id %>
    <%= f.input :date %>
    <%= f.input :description %>
	<%= f.input :ppu, :collection => Job.all.collect { |j| [j.name, j.price]} %>
    <%= f.input :qtt %>
	
   
  </div>

  <div class="actions">
    <%= f.button :submit %>
  </div>
<% end %>

app/views/blips/create.js.erb
//page.insert_html :bottom, :blips, :partial => @blip
//page[@blip].visual_effect :highlight
//page[:new_blip].reset 

//$("#blips-notice").html('<div class="flash notice">hello</div>');


/* Add the new comment to the bottom of the comments list */
$("#blips").append("<%= escape_javascript(render(@blip)) %>");

/* Highlight the new comment */
$("#blips_<%= @blip.id %>").effect("highlight", {}, 3000);
//$("#blip_<%= @blip.id %>").toggle();


/* Reset the comment form */
$("#new_blip").get(0).reset();

app/views/blips/destroy.js.erb
$('#blip_<%= @blip.id %>').fadeOut();

app/views/blips/edit.html.erb
<h1>Editing blip</h1>

<%= render 'form' %>

<%= link_to 'Show', @blip %> |
<%= link_to 'Back', invoices_path %>

app/views/blips/index.html.erb
<h1>Listing blips</h1>

<table>
  <tr>
    <th>Invoice</th>
    <th>Date</th>
    <th>Description</th>
    <th>Ppu</th>
    <th>Qtt</th>
    <th>Price</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @blips.each do |blip| %>
  <tr>
    <td><%= blip.invoice_id %></td>
    <td><%= blip.date %></td>
    <td><%= blip.description %></td>
    <td><%= blip.ppu %></td>
    <td><%= blip.qtt %></td>
    <td><%= blip.price %></td>
    <td><%= link_to 'Show', blip %></td>
    <td><%= link_to 'Edit', edit_blip_path(blip) %></td>
    <td><%= link_to 'Destroy', blip, :confirm => 'Are you sure?', :method => :delete %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Blip', new_blip_path %>

app/views/blips/new.html.erb
<h1>New blip</h1>

<%= render 'form' %>

<%= link_to 'Back', blips_path %>

app/views/blips/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Invoice:</b>
  <%= @blip.invoice_id %>
</p>

<p>
  <b>Date:</b>
  <%= @blip.date %>
</p>

<p>
  <b>Description:</b>
  <%= @blip.description %>
</p>

<p>
  <b>Ppu:</b>
  <%= @blip.ppu %>
</p>

<p>
  <b>Qtt:</b>
  <%= @blip.qtt %>
</p>

<p>
  <b>Price:</b>
  <%= @blip.price %>
</p>


<%= link_to 'Edit', edit_blip_path(@blip) %> |
<%= link_to 'Back', blips_path %>